@startuml GestionUsuarios

left to right direction
skinparam packageStyle rectangle
skinparam actorStyle stick

skinparam usecase {
    BackgroundColor #B3D9FF
    BorderColor #3399FF
    FontColor Black
}

skinparam actor {
    BackgroundColor #FFD699
    BorderColor Black
    FontColor Black
}

actor Administrador #B3D9FF

package "Gestión de usuarios – SIGMA" {
    usecase "Crear_usuario" as CU
    usecase "Actualizar_usuario" as AU
    usecase "Inactivar_usuario" as EU
    usecase "Buscar_usuario" as BU
}

Administrador -- CU
Administrador -- AU
Administrador -- EU
Administrador -- BU


@enduml
