@startuml BuscarCategoríasProductos
left to right direction
skinparam backgroundColor White
skinparam usecase {
    BackgroundColor #ADD8E6
    BorderColor Black
    ArrowColor Black
}

actor Administrador

skinparam actor {
    BackgroundColor #ADD8E6
    BorderColor Black
    FontColor Black
}

rectangle "Buscar_categorías_productos - SIGMA" {
    usecase "Buscar categorías y productos\n―――――――――――――\n<b>extension points</b>\nAplicar filtros adicionales\n Exportar resultados a un archivo" as CU
    usecase "Exportar resultados a un archivo" as ER
    usecase "Aplicar filtros adicionales" as AP
    usecase "Mostrar resultados" as MR
    usecase "Realizar búsqueda en sistema" as RB
    usecase "Ingresar parámetros de búsqueda" as IP
    usecase "Identificarse" as ID
}

Administrador -- CU

CU ..> (ID) : <<Include>>
CU ..> (IP) : <<Include>>
CU ..> (RB) : <<Include>>
CU ..> (MR) : <<Include>>
CU <.. (AP) : <<Extend>>
CU <.. (ER) : <<Extend>>

@enduml
